# Generated by Django 4.2.7 on 2023-11-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='updated_at',
        ),
    ]
