# Generated by Django 4.2.7 on 2023-11-09 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=200)),
                ('operating_hours', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='charging_station_images/')),
                ('contact_info', models.CharField(max_length=100)),
                ('operational_status', models.BooleanField(default=True)),
            ],
        ),
    ]
