# Generated by Django 4.2.7 on 2023-11-20 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentIntegration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
